version: '3.8'

services:
  web:
    container_name: denisa-portfolio
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - RESEND_API_KEY=re_ajMzJoCy_C76Ubqh4CikKC7dKtDnezP17
      - RESEND_FROM_EMAIL=onboarding@resend.dev
      - CONTACT_EMAIL=denisa@taskyo.cz
      # Tímto zajistíme, že Next.js build bude ignorovat chyby i v Dockeru
      - NEXT_TELEMETRY_DISABLED=1